# Generated by Django 3.2 on 2023-04-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comfirmation_code',
            field=models.TextField(null=True, verbose_name='Код подтверждения'),
        ),
    ]
