# Generated by Django 3.2 on 2023-04-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_comfirmation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='comfirmation_code',
            new_name='confirmation_code',
        ),
    ]
